// Supplemental messages absent from the pinned engine's language catalogue.
// ${...} captures are deliberately opaque: paths, vault names and codes are user data.
export default Object.fromEntries([
["The server does not accept this version of ArcaLink. Update the plugin and sign in again. If no update is available, contact support.", "Сервер не принимает эту версию ArcaLink. Обновите плагин и повторно войдите в аккаунт. Если обновления нет, обратитесь в поддержку."],
["Synchronisation paused. Your local notes are preserved. The server does not accept this version of ArcaLink. Update the plugin and sign in again. If no update is available, contact support.", "Синхронизация приостановлена. Локальные заметки сохранены. Сервер не принимает эту версию ArcaLink. Обновите плагин и повторно войдите в аккаунт. Если обновления нет, обратитесь в поддержку."],
["Synchronisation paused. Your local notes are preserved. Sign in again in the ArcaLink settings.", "Синхронизация приостановлена. Локальные заметки сохранены. Повторно войдите в аккаунт в настройках ArcaLink."],
["Synchronisation paused. Your local notes are preserved. Access to synchronisation was denied. Check your account in the ArcaLink settings. If the error persists, contact support.", "Синхронизация приостановлена. Локальные заметки сохранены. Нет доступа к синхронизации. Проверьте аккаунт в настройках ArcaLink. Если ошибка остаётся, обратитесь в поддержку."],
["Synchronisation paused. Your local notes are preserved. The server is busy. Wait a little and try synchronising again.", "Синхронизация приостановлена. Локальные заметки сохранены. Сервер занят. Подождите немного и повторите синхронизацию."],
["Synchronisation paused. Your local notes are preserved. Could not prepare synchronisation. Try again. If the error persists, contact support.", "Синхронизация приостановлена. Локальные заметки сохранены. Не удалось подготовить синхронизацию. Повторите попытку. Если ошибка остаётся, обратитесь в поддержку."],
["Plan: ${p0}. Status: ${p1}.", "Тариф: ${p0}. Статус: ${p1}."],
["active", "активна"],
["grace period", "льготный период"],
["awaiting payment", "ожидается оплата"],
["suspended", "приостановлена"],
["cancelled", "отменена"],
["not specified", "не указан"],
["unknown", "не определён"],
["MB", "МБ"],
["Account", "Аккаунт"],
["Workspaces", "Хранилища"],
["Sync", "Синхронизация"],
["Collaboration", "Совместная работа"],
["Quick guide", "Краткая инструкция"],
["Release notes", "История изменений"],
["ArcaLink settings sections", "Разделы настроек ArcaLink"],
["Workspace", "Хранилище"],
["Storage space", "Место в хранилище"],
["Not loaded yet", "Данные пока не загружены"],
["Storage usage", "Заполнение хранилища"],
["Personal note encryption", "Шифрование личных заметок"],
["Server workspaces", "Серверные хранилища"],
["Refresh list", "Обновить список"],
["Register and download", "Регистрация и скачивание"],
["Shared notes", "Совместные заметки"],
["Create note", "Создать заметку"],
["Shared note", "Совместная заметка"],
["Title", "Название"],
["Join", "Присоединиться"],
["Invitation code", "Код приглашения"],
["Checking account sign-in…", "Проверяем вход в аккаунт…"],
["Not signed in", "Вход не выполнен"],
["Subscription", "Подписка"],
["Sign in in the workspace settings", "Войдите в настройках хранилища"],
["Free: relay without a cloud copy", "Free: ретрансляция без облачной копии"],
["Files are stored only on devices", "Файлы хранятся только на устройствах"],
["Both devices must be open", "Оба устройства должны быть открыты"],
["Connect a workspace to view your subscription", "Подключите хранилище для просмотра подписки"],
["Sign in to view your subscription", "Войдите в аккаунт для просмотра подписки"],
["Connect a workspace to view available storage", "Подключите хранилище для просмотра свободного места"],
["Connection saved. Checking the server workspace name…", "Подключение сохранено. Проверяем название серверного хранилища…"],
["Account check", "Проверка аккаунта"],
["Reload sign-in and subscription status.", "Повторить загрузку статуса входа и подписки."],
["Check again", "Повторить проверку"],
["Workspace check", "Проверка хранилища"],
["Refresh connection and available storage information.", "Обновить сведения о подключении и свободном месте."],
["Refresh information", "Обновить данные"],
["Email address", "Электронная почта"],
["Account email", "Почта аккаунта"],
["Password", "Пароль"],
["Sign in to ArcaLink", "Вход в ArcaLink"],
["Sign in", "Войти"],
["Password recovery", "Восстановление пароля"],
["Recover password", "Восстановить пароль"],
["Automatic sync", "Автоматическая синхронизация"],
["Sync notes when they change and when the app starts.", "Синхронизировать заметки при изменениях и запуске приложения."],
["Sync plugins", "Синхронизировать плагины"],
["Storage warning", "Предупреждение о заполнении"],
["Notify at 95% of account storage capacity. Checked at startup and every 5 minutes.", "Автоматическое уведомление при заполнении 95% квоты аккаунта. Проверка при запуске и каждые 5 минут."],
["Sync log", "Журнал синхронизации"],
["Show log", "Показать лог"],
["Connection check", "Диагностика подключения"],
["Check server access and available storage.", "Проверить доступ к серверу и свободное место."],
["Check connection", "Проверить подключение"],
["Open the ArcaLink website", "Открыть сайт ArcaLink"],
["ArcaLink — open website", "ArcaLink — перейти на сайт"],
["Sync notes between devices. Use the same account on every device. Do not enable other sync plugins at the same time.", "Синхронизация заметок между устройствами. На всех устройствах используйте один аккаунт. Не включайте одновременно другие плагины синхронизации."],
["No workspace connected. To download notes, select the same server workspace as on your first device.", "Хранилище не подключено. Для скачивания заметок выберите то же серверное хранилище, что и на первом устройстве."],
["Your encryption preference is saved. You can change it after connecting cloud storage.", "Настройка шифрования сохранена. Изменить её можно после подключения облачного хранилища."],
["Enabled. Changing encryption moves notes to a new server workspace.", "Включено. Смена режима переносит заметки в новое серверное хранилище."],
["Disabled. The server can read personal notes. Changing encryption moves data to a new workspace.", "Выключено. Сервер может читать личные заметки. Смена режима переносит данные в новое хранилище."],
["First sign in on the Account tab. Then select a server workspace and click Connect.", "Сначала войдите в аккаунт на вкладке «Аккаунт». Затем выберите серверное хранилище и нажмите «Подключить»."],
["Select a server workspace and click Connect to confirm. Creating a workspace does not change your current connection.", "Выберите серверное хранилище и подтвердите действие кнопкой «Подключить». Создание хранилища не меняет текущее подключение."],
["Edit notes together. The server can read their text. Invite an editor or reader from the command palette. All participants need an up-to-date plugin.", "Редактируйте заметки вместе. Сервер видит их текст. Пригласить редактора или читателя можно через палитру команд. Всем участникам нужна актуальная версия плагина."],
["Signing in does not connect a workspace. Select one on the Workspaces tab and click Connect. If already signed in, you can leave the password blank.", "Вход не подключает хранилище. Выберите его на вкладке «Хранилища» и нажмите «Подключить». Если вход уже выполнен, пароль можно не вводить."],
["Get a code by email and set a new password on the ArcaLink website. Then sign in here with the new password.", "Получите код на почту и задайте новый пароль на сайте ArcaLink. Затем войдите здесь с новым паролем."],
["Could not load your subscription. Try again later.", "Не удалось загрузить подписку. Повторите проверку позже."],
["The server returned invalid storage information", "Сервер вернул некорректные данные о хранилище"],
["Could not load available storage information.", "Не удалось загрузить данные о свободном месте."],
["Free does not store files on the server. Cloud sync is disabled. See workspace settings for the retention period of your previous copy. Renew Begin or Pro to restore cloud sync.", "Free не хранит файлы на сервере. Облачная синхронизация отключена. Срок хранения прежней копии указан в настройках хранилища. Для облачной синхронизации продлите Begin или Pro."],
["Connection saved, but the server name could not be verified. On the Workspaces tab, check that you selected the same server workspace as on the first device.", "Подключение сохранено, но название сервера проверить не удалось. На вкладке «Хранилища» проверьте, что выбран тот же сервер, что и на первом устройстве."],
["Transfer third-party plugin files and settings between devices. Enable this on every device. ArcaLink connection settings and service files are excluded. Enable new plugins manually; restart Obsidian after their files are updated.", "Передавать файлы и настройки сторонних плагинов между устройствами. Включите на каждом устройстве. Настройки подключения и служебные файлы ArcaLink не передаются. Новые плагины включайте вручную; после обновления файлов перезапустите Obsidian."],
["Signed in: ${p0}", "Вход выполнен: ${p0}"],
["Local workspace “${p0}” is connected to server workspace “${p1}”. Select the same server workspace on every device to exchange notes.", "Локальное хранилище «${p0}» подключено к серверному «${p1}». Для обмена заметками на всех устройствах выберите одно и то же серверное хранилище."],
["Used ${p0} of ${p1}. Available ${p2}.", "Занято ${p0} из ${p1}. Свободно ${p2}."],
["${p0}% used", "${p0}% занято"],
["Installed version ${p0}. Recent ArcaLink plugin changes are listed here.", "Установлена версия ${p0}. Здесь перечислены последние изменения плагина ArcaLink."],
["Version ${p0}", "Версия ${p0}"],
["Initial public release of ArcaLink Sync for the Obsidian Community catalogue.", "Первый публичный выпуск ArcaLink Sync для каталога сообщества Obsidian."],
["Personal workspace sync between devices, shared folders, collaborative editing, and notes from Telegram.", "Синхронизация личных хранилищ между устройствами, общие папки, совместное редактирование и получение заметок из Telegram."],
["On the Account tab, sign in to ArcaLink. If you do not have an account, open Register and download. Forgot your password? Click Recover password.", "На вкладке «Аккаунт» войдите в ArcaLink. Если аккаунта ещё нет, откройте «Регистрация и скачивание». Забыли пароль — нажмите «Восстановить пароль»."],
["On the Workspaces tab, select a server workspace and click Connect. You can create a new one separately; creating it does not change your current connection.", "На вкладке «Хранилища» выберите серверное хранилище и нажмите «Подключить». Создать новое можно отдельно: создание не меняет текущее подключение."],
["Connecting or switching a server workspace merges local and server notes. Read the warning and confirm the merge. Back up important notes before the first connection.", "При подключении или смене серверного хранилища локальные и серверные заметки объединяются. Прочитайте предупреждение и подтвердите слияние. Перед первым подключением сохраните резервную копию важных заметок."],
["On your second device, sign in to the same account and connect the same server workspace. Wait for the merge and download to finish.", "На втором устройстве войдите в тот же аккаунт и подключите то же серверное хранилище. Дождитесь завершения слияния и загрузки заметок."],
["On the Sync tab, enable automatic sync. If needed, enable Sync plugins on every device; activate new plugins manually and restart Obsidian after their files are updated.", "На вкладке «Синхронизация» включите автоматическую синхронизацию. При необходимости включите «Синхронизировать плагины» на каждом устройстве; новые плагины активируйте вручную, после обновления их файлов перезапустите Obsidian."],
["The indicator at the bottom shows sync status. Hover to read messages or click to open settings. The detailed log is available under Sync → Show log.", "Лампочка внизу показывает состояние синхронизации. Наведите мышь, чтобы прочитать сообщения; нажмите, чтобы открыть настройки. Подробный журнал доступен через «Синхронизация» → «Показать лог»."],
["Encryption, available storage, and server workspace management are on the Workspaces tab. Shared notes and folders are under Collaboration, and the bot is under Telegram. Install updates through the Obsidian plugin catalogue.", "Режим шифрования, свободное место и управление серверными хранилищами находятся во «Хранилищах». Совместные заметки и общие папки — в «Совместной работе», бот — в «Telegram». Обновления устанавливаются через каталог плагинов Obsidian."],
['Interface language', 'Язык интерфейса'],
['Choose the language for ArcaLink settings and notifications.', 'Выберите язык настроек и уведомлений ArcaLink.'],
['Same as Obsidian', 'Как в Obsidian'],
['Could not save the interface language. Try again.', 'Не удалось сохранить язык интерфейса. Повторите попытку.'],
['Connection settings are saved. Restart Obsidian to start syncing. Restart now?', 'Настройки подключения сохранены. Для начала синхронизации нужно перезапустить Obsidian. Перезапустить сейчас?'],
['Yes, restart immediately', 'Да, перезапустить сейчас'],
['Yes, schedule a restart after stabilisation', 'Да, перезапустить после завершения текущих операций'],
['No, Leave it to me', 'Нет, я перезапущу позже'],
['Configured', 'Настроено'],
['Unavailable on the current plan', 'Недоступно на текущем тарифе'],
['Creating shared notes, shared folders and invitations requires Pro. Saved content and access management remain available.', 'Создание совместных заметок, общих папок и приглашений доступно на Pro. Сохранённые материалы и управление доступом остаются на месте.'],
['This feature requires a plan with server storage. Saved settings are retained.', 'Для этой функции нужен тариф с серверным хранилищем. Сохранённые настройки остаются на месте.'],
['Hiding on close is unavailable: Obsidian does not report application exit.', 'Сворачивание при закрытии недоступно: Obsidian не сообщает о выходе из приложения.'],
["Tray and hotkeys", "Трей и горячие клавиши"],
["Window controls are unavailable in this Obsidian build.", "Управление окном недоступно в этой сборке Obsidian."],
["Show or hide window", "Показать или скрыть окно"],
["Create quick note", "Создать быструю заметку"],
["Sync now", "Синхронизировать сейчас"],
["ArcaLink settings", "Настройки ArcaLink"],
["Close this vault", "Закрыть это хранилище"],
["Could not create the tray icon.", "Не удалось создать значок в трее."],
["Hotkey unavailable or already in use: ${p0}", "Горячая клавиша недоступна или занята: ${p0}"],
["Hiding disabled: enable a working tray icon or show-window hotkey.", "Сворачивание отключено: включите рабочий значок в трее или горячую клавишу показа окна."],
["To hide the window, enable a working tray icon or show-window hotkey.", "Для сворачивания включите рабочий значок в трее или горячую клавишу показа окна."],
["Could not save tray and hotkey settings.", "Не удалось сохранить настройки трея и горячих клавиш."],
["Invalid quick-note folder.", "Недопустимая папка для быстрых заметок."],
["Quick note", "Быстрая заметка"],
["Could not create a quick note. Check the folder and vault access.", "Не удалось создать быструю заметку. Проверьте папку и доступ к хранилищу."],
["Tray and global hotkeys are available on desktop only.", "Трей и глобальные горячие клавиши доступны только на компьютере."],
["These settings are stored on this device only. Global hotkeys work outside Obsidian too. Use different shortcuts in other local vaults to avoid conflicts.", "Эти настройки сохраняются только на этом устройстве. Глобальные клавиши работают и вне Obsidian. В других локальных хранилищах задайте другие сочетания, чтобы избежать конфликта."],
["Settings are ready to use.", "Настройки готовы к использованию."],
["Tray icon", "Значок в трее"],
["Menu for showing the window, quick notes, sync and settings. On macOS, the icon is in the menu bar.", "Меню показа окна, быстрой заметки, синхронизации и настроек. На macOS значок находится в строке меню."],
["Hide when closing the window", "Сворачивать при закрытии окна"],
["Closing the window keeps this vault running in the background. To exit, choose “Close this vault” in the tray menu.", "Закрытие окна оставляет это хранилище работать в фоне. Для выхода выберите «Закрыть это хранилище» в меню трея."],
["Global hotkeys", "Глобальные горячие клавиши"],
["Do not replace Obsidian hotkeys. Unavailable shortcuts are shown below.", "Не заменяют горячие клавиши Obsidian. Занятые сочетания показаны ниже."],
["Save the shortcut with “Apply”. Leave the field empty to disable this hotkey.", "Сочетание сохраняется кнопкой «Применить». Пустое поле отключает эту клавишу."],
["Apply", "Применить"],
["Quick-note folder", "Папка быстрых заметок"],
["Path inside the local vault. An empty field means the vault root.", "Путь внутри локального хранилища. Пустое поле — корень хранилища."],
["Test window controls", "Проверка управления окном"],
["Hide to tray", "Свернуть в трей"],
["Obsidian hotkeys", "Горячие клавиши Obsidian"],
["These commands are also available in the command palette. For shortcuts within Obsidian, use its “Hotkeys” section.", "Эти команды также доступны в палитре команд. Для сочетаний внутри Obsidian используйте его раздел «Горячие клавиши»."],
["Open hotkeys", "Открыть горячие клавиши"],
["Restored tray, hiding on window close, and global hotkeys for showing the window and quick notes.", "Возвращены трей, сворачивание при закрытии окна и глобальные горячие клавиши для показа окна и быстрой заметки."],
["Added a dedicated settings tab. The window cannot be hidden without a working way to show it again.", "Добавлена отдельная вкладка настроек. Без рабочего способа возврата окно не скрывается."],

['Linked Telegram users', 'Привязанные пользователи Telegram'],
['Telegram username restriction', 'Ограничение по имени пользователя Telegram'],
['Optional: a username without @ restricts messages to one user. For multiple users, leave this field blank. Each user must link separately with a one-time code.', 'Необязательно: имя без @ ограничивает приём одним пользователем. Для нескольких пользователей оставьте поле пустым. Каждый пользователь должен отдельно привязаться одноразовым кодом.'],
['Create a separate code for each user and send them /start CODE. The ID is the permanent Telegram user identifier. Disconnecting a user does not delete notes or disconnect others.', 'Для каждого пользователя создайте отдельный код и передайте ему команду /start КОД. ID — постоянный идентификатор пользователя Telegram. Отключение пользователя не удаляет заметки и не отключает остальных.'],
['Loading users…', 'Загрузка пользователей…'],
['Linked users: ${p0}', 'Привязано пользователей: ${p0}'],
['No users linked yet. Click “Add user”.', 'Пользователи ещё не привязаны. Нажмите «Добавить пользователя».'],
['Telegram user · ID ${p0}', 'Пользователь Telegram · ID ${p0}'],
['Linked', 'Привязан'],
['Linked on: ${p0}', 'Дата привязки: ${p0}'],
['Messages restricted to @${p0}', 'Приём ограничен именем @${p0}'],
['Messages are delivered to all selected workspaces.', 'Сообщения поступают во все выбранные хранилища.'],
['Add user', 'Добавить пользователя'],
['Add Telegram user', 'Добавить пользователя Telegram'],
['Disconnect user', 'Отключить пользователя'],
['User disconnected from the bot', 'Пользователь отключён от бота'],
['Refresh user list', 'Обновить список пользователей'],
['Could not refresh users: ${p0}', 'Не удалось обновить список пользователей: ${p0}'],
['Could not load users: ${p0}', 'Не удалось загрузить пользователей: ${p0}'],
['Messages are currently restricted to @${p0}. To add other users, clear the restriction in the bot settings and save them.', 'Сейчас приём ограничен именем @${p0}. Для добавления других пользователей очистите ограничение в настройках бота и сохраните их.'],
['Send this command only to the user you want to add. The code is single-use; generate another code for the next user.', 'Передайте команду только тому пользователю, которого хотите подключить. Код одноразовый; для следующего пользователя создайте новый.'],
['Migrating existing remote configuration to sls+ format...', 'Перенос сохранённых параметров подключения…'],
['Conflicting changes', 'Конфликтующие изменения'],
['Some files have been left conflicted! Press {HERE} to resolve them, or you can do it later by "Pick a file to resolve conflict', 'В некоторых заметках остались конфликтующие версии. Нажмите {HERE}, чтобы выбрать нужную версию. Это можно сделать позже командой «Выбрать файл для разрешения конфликта».'],
['Some files have been left conflicted! Please resolve them by "Pick a file to resolve conflict". The list is written in the log.', 'В некоторых заметках остались конфликтующие версии. Используйте команду «Выбрать файл для разрешения конфликта». Список заметок доступен в журнале.'],
['Setting markdown ${p0} (This is not-active file) has been detected. Apply this from {HERE}.', 'Обнаружен файл настроек ${p0} (это не основной файл настроек). Нажмите {HERE}, чтобы применить настройки.'],
['Setting markdown ${p0} has been detected. Apply this from {HERE}.', 'Обнаружен файл настроек ${p0}. Нажмите {HERE}, чтобы применить настройки.'],
['Pick a version', 'Выберите версию'],
['Vault and database revision', 'Версии локального файла и базы'],
['Vault file', 'Локальный файл'],
['Database revision', 'Версия в базе'],
['Base', 'Основная версия'],
['Conflicted', 'Конфликтующая версия'],
['Local', 'Локальная версия'],
['Remote', 'Серверная версия'],
['Use Base', 'Использовать основную версию'],
['Use Conflicted', 'Использовать конфликтующую версию'],
['Use Local', 'Использовать локальную версию'],
['Use Remote', 'Использовать серверную версию'],
['Use ${p0}', 'Использовать ${p0}'],
['Concat both', 'Объединить обе версии'],
['▲ Prev', '▲ Назад'],
['▼ Next', '▼ Вперёд'],
['(Too large diff to display)', '(Различия слишком велики для отображения)'],
['Show log', 'Показать журнал'],
['Show history', 'Показать историю'],
['Pick a file to show history', 'Выбрать файл для просмотра истории'],
['Document History', 'История документа'],
['Highlight diff', 'Подсветить различия'],
['Diff only', 'Только различия'],
['Copy to clipboard', 'Копировать в буфер обмена'],
['Back to this revision', 'Восстановить эту версию'],
['Search in history (last 100)...', 'Поиск по истории (последние 100 версий)…'],
['Previous match', 'Предыдущее совпадение'],
['Next match', 'Следующее совпадение'],
['Older revision', 'Предыдущая версия'],
['Newer revision', 'Следующая версия'],
['Loading old revisions...', 'Загрузка предыдущих версий…'],
['Searching...', 'Поиск…'],
['Searching ${p0}/${p1}...', 'Поиск: ${p0}/${p1}…'],
['Rev ${p0}/${p1}', 'Версия ${p0}/${p1}'],
['${p0} / ${p1} revisions', '${p0} / версий: ${p1}'],
['${p0}/${p1} matches', 'Совпадения: ${p0}/${p1}'],
['No matches found', 'Совпадений не найдено'],
['Done', 'Готово'],
['Modified:${p0}', 'Изменено: ${p0}'],
['We don\'t have any history for this note.', 'Для этой заметки ещё нет истории.'],
['Error while loading file.', 'Ошибка загрузки файла.'],
['Could not read this revision', 'Не удалось прочитать эту версию'],
['Binary file', 'Двоичный файл'],
['(At this revision, the file has been deleted)', '(В этой версии файл был удалён)'],
['Failed to open Node key-value database', 'Не удалось открыть служебную базу Node.'],
['Failed to reset Node key-value database', 'Не удалось сбросить служебную базу Node.'],
['Failed to import ${p0}: ${p1}', 'Не удалось импортировать ${p0}: ${p1}'],
['Failed to clean up after start failure: ${p0}', 'Не удалось завершить очистку после сбоя запуска: ${p0}'],
['Failed to start: ${p0}', 'Не удалось запустить: ${p0}'],
['Error scanning directory \'${p0}\': ${p1}', 'Ошибка проверки папки «${p0}»: ${p1}'],
['Failed to save snapshot: ${p0}', 'Не удалось сохранить снимок: ${p0}'],
['Error processing ${p0} event for ${p1}: ${p2}', 'Ошибка обработки события ${p0} для ${p1}: ${p2}'],
['Failed to start FileSystemObserver: ${p0}', 'Не удалось запустить наблюдение за файлами: ${p0}'],
['Error stopping observer: ${p0}', 'Ошибка при остановке наблюдения за файлами: ${p0}'],
['Something happened at enumerating customization :${p0}', 'Ошибка при просмотре настроек: ${p0}'],
['Migrating ${p0} to V2', 'Перенос ${p0} в формат V2.'],
['[⚙ Initialise]', '[⚙ Подготовка]'],
['Error fetching document ${p0} / ${p1}: $', 'Ошибка загрузки документа ${p0} / ${p1}: $'],
['Analysing database: ${p0} (${p1}) / ${p2}', 'Анализ базы: ${p0} (${p1}) / ${p2}'],
['Restoring the selected revision failed before Vault reflection completed. Review the file with \'Inspect conflicts and file/database differences\' before retrying.', 'Восстановление выбранной версии завершилось ошибкой до применения к локальным файлам. Перед повторной попыткой проверьте файл через проверку конфликтов и различий файла и базы.'],
['The restored revision was saved in the local database, but it could not be reflected to the Vault. Use \'Inspect conflicts and file/database differences\' to review and apply it.', 'Восстановленная версия сохранена в локальной базе, но не применена к файлам. Используйте проверку конфликтов и различий файла и базы для проверки и применения.'],
['The selected content was restored as a new revision. Other versions remain unresolved; use \'Inspect conflicts and file/database differences\' to review them.', 'Выбранное содержимое восстановлено как новая версия. Другие версии ещё не согласованы; проверьте конфликты и различия файла и базы.'],
['The selected content was restored as a new revision. LiveSync could not confirm whether other versions remain; use \'Inspect conflicts and file/database differences\' to review the file.', 'Выбранное содержимое восстановлено как новая версия. Не удалось проверить наличие других версий; проверьте конфликты и различия файла и базы.'],
['Migration to IndexedDB completed. Obsidian will be restarted with new configuration immediately.', 'Перенос в IndexedDB завершён. Obsidian будет сейчас перезапущен с новыми настройками.'],
['Migration to IDB completed. Obsidian will be restarted with new configuration immediately.', 'Перенос в IDB завершён. Obsidian будет сейчас перезапущен с новыми настройками.'],
['Migrating all data to IndexedDB...', 'Перенос всех данных в IndexedDB…'],
['Migration to IndexedDB completed. Please switch the adapter and restart Obsidian.', 'Перенос в IndexedDB завершён. Выберите новый адаптер и перезапустите Obsidian.'],
['Migrating all data to IDB...', 'Перенос всех данных в IDB…'],
['Migration to IDB completed. Please switch the adapter and restart Obsidian.', 'Перенос в IDB завершён. Выберите новый адаптер и перезапустите Obsidian.'],
['Suffix has been changed. Reopening database...', 'Суффикс изменён. База открывается заново…'],
['Remediation setting changed. Restarting Obsidian...', 'Параметр восстановления изменён. Перезапуск Obsidian…'],
['Opening destination database for migration: ${p0}.', 'Открытие целевой базы для переноса: ${p0}.'],
['Destroyed existing destination database for migration: ${p0}.', 'Предыдущая целевая база для переноса удалена: ${p0}.'],
['Re-created destination database for migration: ${p0}.', 'Целевая база для переноса создана заново: ${p0}.'],
['Remediation mode is active, so the detailed fetch flow is used instead of Simple Fetch.', 'Включён режим восстановления; вместо простой загрузки используется подробная процедура.'],
['Database active-size: ${p0}, external-size:${p1}, file-size: ${p2}', 'Размеры базы: активных данных ${p0}, внешних данных ${p1}, файла ${p2}.'],
['Processed database active-size: ${p0}, external-size:${p1}, file-size: ${p2}', 'Размеры обработанной базы: активных данных ${p0}, внешних данных ${p1}, файла ${p2}.'],
['Reduced sizes: active-size: ${p0}, external-size:${p1}, file-size: ${p2}', 'Уменьшение размеров: активных данных ${p0}, внешних данных ${p1}, файла ${p2}.'],
['${p0} on Eden', '${p0} во встроенных блоках'],
['${p0} on Metadata', '${p0} в метаданных'],
['${p0} on Path', '${p0} в пути'],
['Rebuilding has been refused: remediation mode is active. Clear the modification-time limit to rebuild.', 'Перестроение запрещено: включён режим восстановления. Для перестроения снимите ограничение времени изменения.'],
['Remediation mode: the files in storage are not stored in the database before fetching.', 'Режим восстановления: локальные файлы не записываются в базу до загрузки серверных данных.'],
['Fast database fetch is available only for CouchDB remote. Falling back to standard fetch.', 'Быстрая загрузка доступна только для CouchDB. Используется обычная загрузка.'],
['Fast database fetch is unavailable while \'Use Internal API\' is enabled. Falling back to Standard Fetch.', 'Быстрая загрузка недоступна при использовании внутреннего API. Используется обычная загрузка.'],
['Checking for incomplete documents...', 'Проверка целостности документов…'],
['Failed to fetch synchronisation parameters', 'Не удалось получить параметры синхронизации с сервера.'],
['Replication has been cancelled by some module failure', 'Синхронизация отменена из-за сбоя модуля.'],
['Failed to initialise the encryption key, preventing replication.', 'Не удалось подготовить ключ шифрования. Синхронизация остановлена.'],
['OneShot Sync begin... (${p0})', 'Начало разовой синхронизации (${p0})…', 'Начало OneShot синхронизации... (${p0})'],
['ArcaLink message language follows the Obsidian settings.', 'Язык сообщений ArcaLink выбран по настройкам Obsidian.', 'Self-hosted LiveSync имеет переводы для вашего языка, поэтому была включена настройка языка Display language.', 'Self-hosted LiveSync had translations for your language, so the Display language setting was enabled.'],
['No size mismatches found', 'Несоответствий размеров не обнаружено'],
['Found ${p0} size mismatches', 'Обнаружено несоответствий размеров: ${p0}'],
['The incomplete document check could not be completed.', 'Не удалось завершить проверку целостности документов.'],
['Incomplete docs check already done, skipping.', 'Проверка целостности документов уже выполнена.'],
['Failed to read file ${p0}: Possibly unprocessed or missing', 'Не удалось прочитать файл ${p0}: возможно, он ещё не обработан или отсутствует.'],
['Failed to save settings: ${p0}', 'Не удалось сохранить настройки: ${p0}'],
['Failed to load settings; using defaults', 'Не удалось загрузить настройки; используются значения по умолчанию.'],
['Failed to initialise LiveSync', 'Не удалось запустить синхронизацию.'],
['LiveSync is not configured yet', 'Синхронизация ещё не настроена.'],
['Connected to ${p0} successfully', 'Подключение к ${p0} установлено.'],
['Connected to ${p0} successfully!', 'Подключение к ${p0} установлено!'],
['Cancelled', 'Отменено'],
['Failed to delete ${p0}', 'Не удалось удалить ${p0}'],
['Failed to delete: ${p0}', 'Не удалось удалить: ${p0}'],
['Could not load ${p0} for comparison: ${p1}${p2}', 'Не удалось загрузить ${p0} для сравнения: ${p1}${p2}'],
['Applying ${p0}.. Failed', 'Не удалось применить ${p0}'],
['Config ${p0} has been applied', 'Настройки ${p0} применены.'],
['Unloading plugin: ${p0}', 'Отключение плагина: ${p0}'],
['Plugin reloaded: ${p0}', 'Плагин перезапущен: ${p0}'],
['Files in ${p0} were updated.', 'Файлы плагина ${p0} обновлены.'],
['Reload ${p0}', 'Перезапустить ${p0}'],
['Other Obsidian settings files were updated.', 'Обновлены другие файлы настроек Obsidian.'],
['Schedule an Obsidian restart', 'Запланировать перезапуск Obsidian'],
['Deleted: ${p0}/${p1} of ${p2} (${p3} items)', 'Удалено: ${p0}/${p1} из ${p2} (элементов: ${p3})'],
['Customisation sync have been temporarily disabled. Please enable them after the fetching, if you need them.', 'Синхронизация настроек временно отключена. При необходимости включите её после загрузки данных.'],
['Failed to process sync file:${p0}', 'Не удалось обработать файл синхронизации: ${p0}'],
['Could not use hidden-file revision ${p0} of ${p1}; the selected revision is no longer live', 'Нельзя использовать версию ${p0} скрытого файла ${p1}: эта версия уже недоступна.'],
['Could not mark hidden file ${p0} as revision ${p1}; the storage content differs', 'Нельзя отметить скрытый файл ${p0} как версию ${p1}: содержимое хранилища отличается.'],
['Requesting remote config for ${p0}. Please input the passphrase on the remote device', 'Запрос настроек для ${p0}. Введите парольную фразу на другом устройстве.'],
['Remote config for ${p0} is not applied', 'Серверные настройки для ${p0} не применены.'],
['The document ID configurations differ. Import the correct Setup URI, or configure the matching ID key, before synchronising.', 'Настройки идентификаторов документов различаются. Перед синхронизацией импортируйте правильную ссылку подключения или задайте соответствующий ключ идентификаторов.'],
['The remote type does not support preferred tweak values.', 'Этот тип сервера не поддерживает рекомендуемые параметры.'],
['Failed to get the preferred tweak values from the remote.', 'Не удалось получить рекомендуемые параметры с сервера.'],
['The settings in the remote database are the same as the local database.', 'Настройки серверной и локальной баз совпадают.'],
['Obsidian will be restarted soon! (Within ${p0} seconds)', 'Obsidian будет перезапущен в течение ${p0} секунд.'],
['Old content copied to clipboard', 'Предыдущее содержимое скопировано в буфер обмена.'],
['Unable to display the file in the editor', 'Не удалось открыть файл в редакторе.'],
['The selected revision does not have a revision identifier.', 'У выбранной версии нет идентификатора.'],
['The selected revision could not be restored because its content is no longer available.', 'Нельзя восстановить выбранную версию: её содержимое уже недоступно.'],
['The current database revision could not be read. The Vault was not changed.', 'Не удалось прочитать текущую версию в базе. Локальное хранилище не изменено.'],
['Only an ordinary valid Vault path can be restored from Document History.', 'Из истории документов можно восстановить только обычный файл с допустимым путём в хранилище.'],
['The restored revision could not be created. The file may have changed during the operation, and the Vault was not changed.', 'Не удалось создать восстановленную версию. Возможно, файл изменился во время операции. Локальное хранилище не изменено.'],
['The selected content was restored as a new revision.', 'Выбранное содержимое восстановлено как новая версия.'],
['The restored file could not be opened in the editor.', 'Не удалось открыть восстановленный файл в редакторе.'],
['Could not parse YAML', 'Не удалось прочитать данные YAML.'],
['This setting file seems to backed up one. Please fix the filename or settingSyncFile value.', 'Похоже, выбран файл резервной копии настроек. Исправьте имя файла или параметр settingSyncFile.'],
['Setting markdown has been detected, but not changed.', 'Обнаружен файл настроек; изменений нет.'],
['Loaded settings have been applied!', 'Загруженные настройки применены!'],
['Connection testing is unavailable for the current settings.', 'Проверка подключения недоступна при текущих настройках.'],
['Passphrase is not valid, please fix it.', 'Парольная фраза неверна. Проверьте её и повторите попытку.'],
['Repair action \'${p0}\' failed', 'Не удалось выполнить восстановление «${p0}».'],
['Failed to find the file in the internal files: ${p0}', 'Не удалось найти служебный файл: ${p0}'],
['Could not compare ${p0} revision ${p1}; the Vault file or selected live revision is no longer readable', 'Не удалось сравнить файл ${p0} с версией ${p1}: файл или выбранная версия уже недоступны для чтения.'],
['Verification no longer reports a problem for ${p0}', 'Проверка больше не обнаруживает проблему с ${p0}.'],
['${p0} failed: ${p1}', 'Сбой ${p0}: ${p1}'],
['Discard database branch ${p0} of ${p1}: ${p2}', 'Отбросить ветвь базы ${p0} файла ${p1}: ${p2}'],
['Discard unreadable revision ${p0} of ${p1}: ${p2}', 'Отбросить недоступную версию ${p0} файла ${p1}: ${p2}'],
['Start inspecting file/database state', 'Начало проверки состояния файлов и базы.'],
['Checking ${p0}/${p1} files', 'Проверка файлов: ${p0}/${p1}'],
['Error while processing ${p0}', 'Ошибка при обработке ${p0}'],
['Error while processing without semaphore ${p0}', 'Ошибка при обработке без блокировки: ${p0}'],
['done', 'завершено'],
['Done!', 'Готово!'],
['${p0} has been converted as conflicted document', '${p0} преобразован в документ с конфликтом версий.'],
['Old ${p0} has been deleted', 'Предыдущая версия ${p0} удалена.'],
['Converting ${p0} Failed!', 'Не удалось преобразовать ${p0}!'],
['${p0} has been converted', '${p0} преобразован.'],
['Something went wrong while converting ${p0}', 'Ошибка при преобразовании ${p0}.'],
['Converting finished', 'Преобразование завершено.'],
['Deleting customization sync data', 'Удаление данных синхронизации настроек.'],
['${p0} items have been removed, to confirm how many items are left, please perform it again.', 'Удалено элементов: ${p0}. Повторите операцию для проверки оставшихся элементов.'],
['Journal received history has been cleared.', 'История полученных записей журнала очищена.'],
['Journal sent history has been cleared.', 'История отправленных записей журнала очищена.'],
['Cleanup has been began', 'Очистка началась.'],
['Cleanup has been completed!', 'Очистка завершена!'],
['Cleanup has been failed!', 'Не удалось выполнить очистку!'],
['Journal exchange history has been cleared.', 'История обмена журналом очищена.'],
['Journal download/upload cache has been cleared.', 'Кеш загрузки и отправки журнала очищен.'],
['Failed to import remote configuration!', 'Не удалось импортировать серверные настройки!'],
['Failed to parse remote configuration \'${p0}\' for editing!', 'Не удалось прочитать серверные настройки «${p0}» для редактирования!'],
['Failed to parse remote configuration \'${p0}\' for fetching settings!', 'Не удалось прочитать серверные настройки «${p0}» для загрузки параметров!'],
['Replicating... Docs replicated: ${p0} / ${p1}', 'Синхронизация… Передано документов: ${p0} / ${p1}'],
['Replication completed for migration: ${p0}.', 'Передача при переносе завершена: ${p0}.'],
['Copied migration documents for migration: ${p0}.', 'Документы для переноса скопированы: ${p0}.'],
['Onboarding cancelled by user.', 'Первоначальная настройка отменена пользователем.'],
['Setup URI dialog cancelled.', 'Ввод ссылки подключения отменён.'],
['Manual configuration cancelled.', 'Ручная настройка отменена.'],
['E2EE configuration cancelled.', 'Настройка шифрования отменена.'],
['No changes in settings detected. Skipping applying settings from wizard.', 'Настройки не изменились. Применение параметров мастера пропущено.'],
['Setting Applied', 'Настройка применена'],
['Settings from wizard applied.', 'Настройки мастера применены.'],
['User cancelled applying settings from wizard.', 'Пользователь отменил применение настроек мастера.'],
['User cancelled applying settings from wizard..', 'Пользователь отменил применение настроек мастера.'],
['The QR configuration could not be decoded or contains unsupported settings.', 'Не удалось прочитать QR-код или в нём содержатся неподдерживаемые настройки.'],
['Error in Setting Save Event', 'Ошибка при сохранении настроек.'],
['LiveSync Disabled.', 'Синхронизация отключена.'],
['LiveSync Enabled.', 'Синхронизация включена.'],
['Self-hosted LiveSync resumed', 'Синхронизация возобновлена.'],
['Self-hosted LiveSync suspended', 'Синхронизация приостановлена.'],
['${p0} is conflicted, merging process has been postponed.', 'В ${p0} обнаружен конфликт версий. Слияние отложено.'],
['${p0} Could not delete conflicted revision ${p1} of ${p2}', '${p0} Не удалось удалить конфликтующую версию ${p1} файла ${p2}.'],
['Could not write the resolved content to the storage: ${p0}', 'Не удалось сохранить результат разрешения конфликта: ${p0}'],
['Merged content cannot be stored:${p0}', 'Не удалось сохранить объединённое содержимое: ${p0}'],
['could not get current revisions:${p0}', 'Не удалось получить текущие версии: ${p0}'],
['could not read conflicted revision ${p0}:${p1}', 'Не удалось прочитать конфликтующую версию ${p0}: ${p1}'],
['[conflict] ${p0} is conflicted. Merging process has been postponed to the file have got opened.', '[конфликт] В ${p0} обнаружен конфликт. Слияние отложено до открытия файла.'],
['Resolving conflicts by newer ones', 'Разрешение конфликтов с выбором новых версий.'],
['Check and Processing ${p0} / ${p1}', 'Проверка и обработка: ${p0} / ${p1}'],
['Concatenated content cannot be stored:${p0}', 'Не удалось сохранить соединённое содержимое: ${p0}'],
['Concatenated saved, but cannot delete conflicted revisions: ${p0}, (${p1})', 'Соединённое содержимое сохранено, но удалить конфликтующие версии не удалось: ${p0}, (${p1}).'],
['Merge: Something went wrong: ${p0}, (${p1})', 'Ошибка слияния: ${p0}, (${p1}).'],
['There are no conflicted documents', 'Документов с конфликтующими версиями нет.'],
['Error while scanning conflicted files...', 'Ошибка при проверке файлов с конфликтующими версиями…'],
['Fetch cancelled by user.', 'Загрузка отменена пользователем.'],
['Fetch exited by user.', 'Пользователь завершил загрузку.'],
['Fetch initialisation cancelled by user.', 'Подготовка загрузки отменена пользователем.'],
['User chose to reboot and re-run the process.', 'Пользователь выбрал перезапуск и повторное выполнение операции.'],
['Simple fetch and scan operation completed.', 'Загрузка и проверка завершены.'],
['Remote configuration selection cancelled.', 'Выбор серверных настроек отменён.'],
['Failed to activate remote configuration: ${p0}', 'Не удалось активировать серверные настройки: ${p0}'],
['No remote configuration selected.', 'Серверные настройки не выбраны.'],
['Fetch everything cancelled by user.', 'Полная загрузка отменена пользователем.'],
['Fetch everything operation completed. Vault files will be gradually synced.', 'Полная загрузка завершена. Файлы хранилища будут постепенно синхронизированы.'],
['Could not read synchronisation settings from the remote.', 'Не удалось прочитать параметры синхронизации с сервера.'],
['Rebuild will use this device\'s synchronisation settings.', 'При перестроении будут использованы настройки синхронизации этого устройства.'],
['Remote configuration matches local configuration. No changes applied.', 'Серверные и локальные настройки совпадают. Изменения не внесены.'],
['Remote configuration applied.', 'Серверные настройки применены.'],
['Remote configuration not applied.', 'Серверные настройки не применены.'],
['Error during vault initialisation process.', 'Ошибка при подготовке хранилища.'],
['Error during vault initialisation.', 'Ошибка при подготовке хранилища.'],
['Rebuild everything cancelled by user.', 'Полное перестроение отменено пользователем.'],
['Rebuild initialisation cancelled by user.', 'Подготовка перестроения отменена пользователем.'],
['Rebuild everything operation completed.', 'Полное перестроение завершено.'],
['SCRAM is detected. All operations are suspended.', 'Обнаружена аварийная остановка SCRAM. Все операции приостановлены.'],
['All operations are suspended as per SCRAM.', 'Все операции приостановлены в соответствии с аварийной остановкой SCRAM.'],
['Logs will be written to the file. This might be a performance impact.', 'Журнал будет записываться в файл. Это может повлиять на производительность.'],
['${p0} Update Self-hosted LiveSync before synchronising.', '${p0} Обновите плагин перед синхронизацией.'],
['Processing ${p0} has been skipped due to file size exceeding the limit', 'Обработка ${p0} пропущена: размер файла превышает лимит.'],
['Error while processing replication result', 'Ошибка при обработке результатов синхронизации.'],
['Failed to gather content of ${p0}', 'Не удалось получить содержимое ${p0}.'],
['Failed to get existing document for ${p0} (${p1}, ${p2})', 'Не удалось получить существующий документ для ${p0} (${p1}, ${p2}).'],
['Database cleanup cancelled: ${p0}', 'Очистка базы отменена: ${p0}'],
['Database cleanup cancelled: feature compatibility could not be checked.', 'Очистка базы отменена: не удалось проверить совместимость.'],
['The remote database has been cleaned.', 'Серверная база очищена.'],
['The local database has been cleaned up.', 'Локальная база очищена.'],
['Replication has been cancelled. Please try it again.', 'Синхронизация отменена. Повторите попытку.'],
['Failed to register protocol handler. This feature may not work in some environments.', 'Не удалось зарегистрировать обработчик ссылок. В некоторых средах эта функция может не работать.'],
['Setup URI copied to clipboard', 'Ссылка подключения скопирована в буфер обмена.'],
['Failed to count compromised chunks in local database', 'Не удалось подсчитать повреждённые блоки в локальной базе.'],
['Failed to count compromised chunks in remote database', 'Не удалось подсчитать повреждённые блоки в серверной базе.'],
['Found compromised chunks : ${p0} in local, ${p1} in remote', 'Обнаружены повреждённые блоки: ${p0} в локальной базе, ${p1} на сервере.'],
['Could not find stub file for ${p0}', 'Не удалось найти описание файла ${p0}.'],
['Failed to restore ${p0} from storage', 'Не удалось восстановить ${p0} из хранилища.'],
['PUT: FAILED: ${p0}', 'Не удалось отправить данные: ${p0}'],
['QR Code size exceeded, switching to aggregator mode', 'Размер QR-кода превышен. Используется передача по частям.'],
['Failed to encode split QR Code (${p0})', 'Не удалось создать QR-код из нескольких частей (${p0}).'],
['Failed to parse settings from decrypted data', 'Не удалось прочитать настройки из расшифрованных данных.'],
['Failed to write buffered chunks for ${p0}', 'Не удалось записать отложенные блоки для ${p0}.'],
['Failed to flush buffered chunks for ${p0}', 'Не удалось сохранить отложенные блоки для ${p0}.'],
['No data to save in ${p0}!! This document may be corrupted in the local database! Please back it up immediately, and report an issue!', 'Нет данных для сохранения ${p0}! Документ в локальной базе может быть повреждён. Немедленно сохраните резервную копию и сообщите об ошибке.'],
['Failed to write document ${p0}', 'Не удалось записать документ ${p0}.'],
['Missing document content!, could not read ${p0}(${p1}) from database.', 'Содержимое документа отсутствует. Не удалось прочитать ${p0} (${p1}) из базы.'],
['Something went wrong on reading ${p0}(${p1}) from database:', 'Ошибка при чтении ${p0} (${p1}) из базы:'],
['The storage file has been changed but exceeds the maximum size. Skipping: ${p0}', 'Файл изменён, но его размер превышает лимит. Пропущен: ${p0}'],
['Restored storage operation failed for ${p0}; the Offline Scanner will reconcile the current state', 'Не удалось повторить сохранённую операцию с ${p0}. Проверка локальных файлов согласует текущее состояние.'],
['Database initialisation was rejected by a required module.', 'Обязательный модуль запретил подготовку базы.'],
['Some module has prevented the database from being ready. The database is initialised but not ready for use.', 'Модуль не позволил завершить подготовку базы. База создана, но пока не готова к работе.'],
['Database reset has been prevented or failed on some modules.', 'Сброс базы запрещён или завершился ошибкой одного из модулей.'],
['Local Database could not be reinitialised after reset.', 'Не удалось подготовить локальную базу после сброса.'],
['Local Database Reset', 'Локальная база сброшена'],
['Collecting unreferenced chunks on ${p0}', 'Поиск неиспользуемых блоков: ${p0}'],
['No unreferenced chunks! ${p0}', 'Неиспользуемых блоков нет: ${p0}'],
['Number of unreferenced chunks on ${p0}: ${p1}', 'Количество неиспользуемых блоков в ${p0}: ${p1}'],
['DryRun of cleaning ${p0} database up: Done', 'Пробная очистка базы ${p0} завершена.'],
['Cleaning unreferenced chunks on remote', 'Удаление неиспользуемых блоков на сервере.'],
['Cleaning unreferenced chunks on local', 'Удаление неиспользуемых блоков в локальной базе.'],
['Cleaning unreferenced chunks done!', 'Удаление неиспользуемых блоков завершено!'],
['Compacting database...', 'Сжатие базы…'],
['Compacting database done', 'Сжатие базы завершено.'],
['Cleaning ${p0} database up: Done', 'Очистка базы ${p0} завершена.'],
['${p0}: Something went wrong on balancing', '${p0}: ошибка при согласовании блоков.'],
['Complement missing chunks between databases', 'Восстановление недостающих блоков между базами.'],
['local -> remote: Done', 'Локальная база → сервер: завершено.'],
['remote -> local: Done', 'Сервер → локальная база: завершено.'],
['Something went wrong on balancing!', 'Ошибка при согласовании блоков!'],
['Complement completed!', 'Восстановление недостающих блоков завершено!'],
['Purging unused ${p0} chunks', 'Удаление неиспользуемых блоков: ${p0}'],
['Purging unused ${p0} chunks...', 'Удаление неиспользуемых блоков: ${p0}…'],
['Local chunk backed up: new:${p0} ,exist:${p1}, error:${p2}', 'Резервная копия локальных блоков: новых ${p0}, существующих ${p1}, ошибок ${p2}.'],
['Purging:  ${p0} / ${p1}', 'Удаление: ${p0} / ${p1}'],
['Purging unused chunks done!: ${p0} chunks has been deleted.', 'Удаление неиспользуемых блоков завершено! Удалено блоков: ${p0}.'],
['Unknown encryption version. Cannot decrypt.', 'Неизвестная версия шифрования. Расшифровка невозможна.'],
['Encryption failed.', 'Не удалось зашифровать данные.'],
['Decryption failed.', 'Не удалось расшифровать данные.'],
['Database updated from ${p0} to ${p1}', 'База обновлена с ${p0} до ${p1}.'],
['Replication activated', 'Синхронизация запущена'],
['Replication callback error', 'Ошибка обработчика синхронизации'],
['Replication completed', 'Синхронизация завершена'],
['Replication denied', 'Синхронизация запрещена'],
['Replication error', 'Ошибка синхронизации'],
['Replication stopped for busy.', 'Синхронизация остановлена: выполняется другая операция.'],
['Replication stopped.', 'Синхронизация остановлена.'],
['Something went wrong during synchronisation. Please check the log!', 'Ошибка синхронизации. Проверьте журнал!'],
['Bulk sending chunks to remote database...', 'Отправка блоков в серверную базу…'],
['↑ Uploading chunks', '↑ Отправка блоков'],
['${p0}/(${p1} done)', '${p0}/(завершено ${p1})'],
['Bulk sending failed.', 'Не удалось отправить блоки.'],
['The remote connectivity check timed out.', 'Истекло время ожидания ответа сервера.'],
['The remote document IDs do not match the configured ID key.', 'Идентификаторы серверных документов не соответствуют настроенному ключу.'],
['The remote database has no compatibility with the running version. Please upgrade the plugin.', 'Серверная база несовместима с текущей версией. Обновите плагин.'],
['The remote database has been rebuilt or corrupted since we have synchronized last time. Fetch rebuilt DB, explicit unlocking or chunk clean-up is required.', 'Серверная база была перестроена или повреждена после последней синхронизации. Требуется загрузить перестроенную базу, явно разблокировать её или очистить блоки.'],
['The remote database has been cleaned up. Fetch rebuilt DB, explicit unlocking or chunk clean-up is required.', 'Серверная база была очищена. Требуется загрузить перестроенную базу, явно разблокировать её или очистить блоки.'],
['Some requested chunks were not found in the remote database.', 'Некоторые запрошенные блоки отсутствуют в серверной базе.'],
['Could not retrieve remote milestone', 'Не удалось получить метку состояния сервера.'],
['Could not connect to the remote database', 'Не удалось подключиться к серверной базе.'],
['Could not check the remote database version', 'Не удалось проверить версию серверной базы.'],
['Journal epoch changed (remote files still present). Epoch updated; caches kept.', 'Версия журнала изменилась; серверные файлы сохранены. Версия обновлена, кеши оставлены.'],
['Journal epoch changed and remote wipe confirmed. Clearing dedupe caches.', 'Версия журнала изменилась, очистка сервера подтверждена. Кеши повторных записей очищаются.'],
['WARNING! Could not delete files.', 'Внимание! Не удалось удалить файлы.'],
['Nothing to delete!', 'Нет файлов для удаления!'],
['${p0} items has been deleted!', 'Удалено элементов: ${p0}!'],
['The remote ID derivation key does not match this device.', 'Серверный ключ идентификаторов не соответствует ключу этого устройства.'],
['Remote Bucket Cleared', 'Серверное файловое хранилище очищено'],
['Something happened on Remote Bucket Clear', 'Ошибка при очистке серверного файлового хранилища'],
['Remote Database Created or Connected', 'Серверная база создана или подключена'],
['Lock remote bucket to prevent data corruption', 'Блокировка серверного файлового хранилища для защиты данных'],
['Unlock remote bucket to prevent data corruption', 'Разблокировка серверного файлового хранилища'],
['Mark this device as \'resolved\'.', 'Отметить это устройство как согласованное.'],
['Error! Could not connected to ${p0}\n${p1}', 'Ошибка! Не удалось подключиться к ${p0}\n${p1}'],
['Could not update remote preferred tweak values', 'Не удалось обновить рекомендуемые параметры сервера.'],
['Could not connect to the remote bucket', 'Не удалось подключиться к серверному файловому хранилищу.'],
['Could not get status of the remote bucket', 'Не удалось получить состояние серверного файлового хранилища.'],
['The managed P2P room could not be prepared or opened.', 'Не удалось подготовить или открыть комнату прямого подключения устройств.'],
['Passphrase is required to transfer the configuration. The peer cannot be decrypt the config', 'Для передачи настроек требуется парольная фраза. Другое устройство не может расшифровать настройки.'],
['Server is not available', 'Сервер недоступен'],
['Passphrase is required to decrypt the configuration. The config cannot be decrypted', 'Для расшифровки настроек требуется парольная фраза.'],
['Error while decrypting the configuration', 'Ошибка при расшифровке настроек.'],
['[P2P] Connection failure detected: ${p0}', '[P2P] Ошибка подключения: ${p0}'],
['Closing P2P Connection', 'Закрытие прямого подключения устройств'],
['STORAGE -> DB : ${p0} has been skipped due to file size exceeding the limit', 'Файлы → база: ${p0} пропущен из-за превышения размера.'],
['STORAGE <- DB : Cloud not read ${p0}, possibly deleted', 'Файлы ← база: не удалось прочитать ${p0}; возможно, он удалён.'],
['STORAGE <- DB : ${p0} has been skipped due to file size exceeding the limit', 'Файлы ← база: ${p0} пропущен из-за превышения размера.'],
['Collecting local files on the DB: ${p0}', 'Сбор локальных файлов в базе: ${p0}'],
['DELETE DATABASE did not delete ${p0}; keeping last-seen record to avoid resurrecting the file', 'Удаление из базы не удалило ${p0}. Последняя запись сохранена, чтобы файл не появился снова.'],
['Error processing ${p0} with action ${p1}', 'Ошибка обработки ${p0} при выполнении ${p1}'],
['Error while synchronising files', 'Ошибка при синхронизации файлов'],
['Processing: ${p0}/${p1}', 'Обработка: ${p0}/${p1}'],
['Synchronisation completed: ${p0} files processed (${p1} completed, ${p2} skipped, ${p3} failed)', 'Синхронизация завершена: обработано файлов ${p0} (готово ${p1}, пропущено ${p2}, ошибок ${p3}).'],
['Initializing', 'Подготовка'],
['Initialize done!', 'Подготовка завершена!'],
['No remote configurations found.', 'Серверные подключения не настроены.'],
['Switched to remote: ${p0}', 'Выбрано серверное подключение: ${p0}'],
['Switched to remote: ${p0} and starting replication...', 'Выбрано серверное подключение ${p0}; начинается синхронизация…'],
['Failed to parse remote! Detailed information is available in verbose logs.', 'Не удалось прочитать серверные настройки. Подробности доступны в диагностическом журнале.'],
['Migration failed! Detailed information is available in verbose logs.', 'Не удалось выполнить перенос! Подробности доступны в диагностическом журнале.'],
['Could not create ${p0}', 'Не удалось создать ${p0}'],
['Could not remove ${p0} after restart preparation failed', 'Не удалось удалить ${p0} после сбоя подготовки перезапуска.'],
['No active replicator found when trying to reset remote database.', 'Нет активного подключения для сброса серверной базы.'],
['Suspending reflection: Database and storage changes will not be reflected in each other until completely finished the fetching.', 'Применение изменений приостановлено: изменения базы и файлов будут согласованы после завершения загрузки.'],
['Database and storage reflection has been resumed!', 'Согласование изменений базы и файлов возобновлено!'],
['Resuming fast database fetch from sequence: ${p0}', 'Возобновление быстрой загрузки базы с позиции ${p0}.'],
['Fast fetch checkpoint found, but the local database is empty. Starting from the beginning.', 'Найдена сохранённая позиция загрузки, но локальная база пуста. Загрузка начнётся заново.'],
['Fast fetch progress: ${p0} / ${p1}\nTotal bytes fetched: ${p2}', 'Быстрая загрузка: ${p0} / ${p1}\nЗагружено байт: ${p2}'],
['Fast fetch interrupted. Retrying from sequence: ${p0}', 'Быстрая загрузка прервана. Повторная попытка с позиции ${p0}.'],
['Fast database fetch completed. Total documents in local database: ${p0}', 'Быстрая загрузка базы завершена. Документов в локальной базе: ${p0}.'],
['Storage kept changing while saving ${p0}; a fresh event is required', 'Файл ${p0} продолжал изменяться при сохранении; требуется новое событие изменения.'],
['Could not store ${p0} on revision ${p1}; the selected revision is no longer live', 'Не удалось сохранить ${p0} как версию ${p1}: выбранная версия уже недоступна.'],
['Could not mark ${p0} as revision ${p1}; the storage content differs', 'Нельзя отметить ${p0} как версию ${p1}: содержимое файла отличается.'],
['Could not preserve the unknown conflict branch for ${p0}; no current revision is available', 'Не удалось сохранить неизвестную конфликтующую ветвь ${p0}: текущая версия недоступна.'],
['Could not preserve the unknown conflict branch for ${p0}', 'Не удалось сохранить неизвестную конфликтующую ветвь ${p0}.'],
['The deleted storage file ${p0} has conflicts, but its displayed revision is unknown; preserving every database branch', 'Удалённый файл ${p0} имеет конфликты, но его отображаемая версия неизвестна. Все ветви базы сохранены.'],
['Refusing to overwrite the existing database entry while renaming ${p0} to ${p1}', 'Перезапись существующей записи базы при переименовании ${p0} в ${p1} запрещена.'],
['Failed to store rename target; preserving source in the database: ${p0}', 'Не удалось сохранить новое имя. Исходная запись базы сохранена: ${p0}'],
['Renamed ${p0} to ${p1}, but preserved every conflicted source branch because the displayed source revision is unknown', '${p0} переименован в ${p1}. Все конфликтующие исходные ветви сохранены: отображаемая исходная версия неизвестна.'],
['Could not apply ${p0} revision ${p1}; the selected revision is no longer live', 'Не удалось применить версию ${p1} файла ${p0}: выбранная версия уже недоступна.'],
['Refusing to overwrite ${p0} while applying the distinct path ${p1}', 'Перезапись ${p0} при применении отдельного пути ${p1} запрещена.'],
['Refusing to apply a filename case change across differently cased parent directories: ${p0} -> ${p1}', 'Изменение регистра имени файла запрещено: регистр родительских папок различается (${p0} → ${p1}).'],
['Could not apply the stored filename case: ${p0} -> ${p1}', 'Не удалось применить сохранённый регистр имени файла: ${p0} → ${p1}.'],
['File ${p0} seems to be corrupted! Writing prevented. (${p1} != ${p2})', 'Возможно, файл ${p0} повреждён! Запись запрещена (${p1} != ${p2}).'],
['Prevented overwriting unsynchronised local changes for ${p0}', 'Перезапись несинхронизированных локальных изменений ${p0} предотвращена.'],
['Preserved unsynchronised local changes as a conflict for ${p0}', 'Несинхронизированные локальные изменения ${p0} сохранены как конфликтующая версия.'],
['Database kept changing while reflecting ${p0}', 'База продолжала изменяться при применении ${p0}.'],
['Preserved ${p0}: the rename target no longer resolves to ${p1}', '${p0} сохранён: новое имя больше не соответствует ${p1}.'],
['Preserved ${p0}: rename target ${p1} is still selected', '${p0} сохранён: новое имя ${p1} всё ещё выбрано.'],
['Preserved ${p0}: a current storage item contradicts its deletion event', '${p0} сохранён: текущий файл противоречит событию удаления.'],
['Could not validate deletion of ${p0}; preserved the database entry', 'Не удалось подтвердить удаление ${p0}. Запись базы сохранена.'],
['Could not validate the saved storage operation for ${p0} against current storage; the Offline Scanner will reconcile the current state', 'Не удалось проверить сохранённую операцию с ${p0} по текущим файлам. Проверка локальных файлов согласует состояние.'],
['Creating missing chunks: ${p0} of ${p1} files', 'Создание недостающих блоков: ${p0} из ${p1} файлов.'],
['Creating chunks Done: ${p0} of ${p1} files', 'Создание блоков завершено: ${p0} из ${p1} файлов.'],
['Failed to reset KeyValueDB', 'Не удалось сбросить служебную базу.'],
['Failed to open KeyValueDB', 'Не удалось открыть служебную базу.'],
['The request may have failed. The reason sent by the server: ${p0}: ${p1}', 'Запрос мог завершиться ошибкой. Ответ сервера: ${p0}: ${p1}'],
['The request was successful by API. But the native fetch API failed! Please check CORS settings on the remote database!. While this condition, you cannot enable LiveSync', 'Сервер ответил через API Obsidian, но встроенный сетевой запрос завершился ошибкой. Проверьте доступность сервера и настройки CORS. Пока ошибка сохраняется, синхронизация недоступна.'],
['Failed to fetch by API. ${p0}: ${p1}', 'Не удалось получить данные через API. ${p0}: ${p1}'],
['Network Error: Failed to fetch: Error:${p0}', 'Сетевая ошибка: не удалось получить данные. Код: ${p0}'],
['Network Error: Failed to fetch', 'Сетевая ошибка: не удалось получить данные'],
['Failed to fetch', 'Не удалось получить данные'],
['Network Error: ${p0}', 'Сетевая ошибка: ${p0}'],
['Network is offline', 'Нет подключения к интернету'],
['No active replicator found', 'Нет активного подключения синхронизации'],
['Active replicator not found during directional ${p0}', 'Не найдено активное подключение для направленной операции ${p0}.'],
['The selected local database is not ready for the rebuild upload.', 'Выбранная локальная база не готова к отправке при перестроении.'],
['The selected local database is not ready for the rebuild download.', 'Выбранная локальная база не готова к загрузке при перестроении.'],
['Active replicator not found during ${p0}', 'Не найдено активное подключение при ${p0}.'],
['Active replicator does not support ${p0}', 'Активное подключение не поддерживает ${p0}.'],
['Legacy remote configuration has been migrated to the remote configuration list.', 'Предыдущие серверные настройки перенесены в список подключений.'],
['Failed to retrieve passphrase. data.json contains unencrypted items!', 'Не удалось получить парольную фразу. Файл data.json содержит незашифрованные параметры!'],
['Remote configuration \'${p0}\' had a plain-text URI marked as encrypted. The flag has been repaired.', 'В серверных настройках «${p0}» незашифрованный адрес был отмечен как зашифрованный. Признак исправлен.'],
['Failed to decrypt configuration item', 'Не удалось расшифровать параметр подключения'],
['Failed to activate the selected remote configuration: ${p0}', 'Не удалось активировать выбранное серверное подключение: ${p0}'],
['Failed to activate the selected P2P remote configuration: ${p0}', 'Не удалось активировать выбранное прямое подключение устройств: ${p0}'],
['Configuration issues detected and automatically resolved. However, unsynchronized data may exist. Consider rebuilding if necessary.', 'Ошибки настроек обнаружены и исправлены автоматически. Возможно, остались несинхронизированные данные. При необходимости выполните перестроение базы.'],
['Device name missing. Disabling plug-in sync.', 'Имя устройства не задано. Синхронизация плагинов отключается.'],
['Synchronisation parameters fetched successfully', 'Параметры синхронизации получены'],
['No remote replicator configuration found. Skipping replicator initialisation.', 'Серверное подключение не настроено. Синхронизация пока не запускается.'],
['Starting OneShot sync... (${p0})', 'Начало разовой синхронизации (${p0})…'],
['Verbose log', 'Подробный журнал'],
['Sync: ${p0}', 'Синхронизация: ${p0}'],
['Invalid pilot release', 'Некорректные данные обновления плагина'],
['Invalid release file', 'Некорректный файл обновления'],
['Invalid update recovery journal', 'Некорректный журнал восстановления обновления'],
['Release integrity check failed: ${p0}', 'Проверка целостности обновления не пройдена: ${p0}'],
['Release manifest mismatch', 'Описание обновления не соответствует версии плагина'],
['Update preparation failed; previous plugin unchanged.', 'Не удалось подготовить обновление. Предыдущий плагин сохранён.'],
['Update failed; rollback incomplete. Reinstall pilot ZIP; data.json was not modified.', 'Обновление завершилось ошибкой; откат не завершён. Переустановите плагин из ZIP. Файл настроек data.json не изменён.'],
['Update failed; previous plugin restored.', 'Обновление завершилось ошибкой. Предыдущая версия плагина восстановлена.'],
['Update already in progress', 'Обновление уже выполняется'],
['ArcaLink request failed', 'Не удалось выполнить запрос ArcaLink'],
['Debug info copied to clipboard. You can paste it in the issue. Be careful as it may contain sensitive information, review it before sharing.', 'Диагностические данные скопированы в буфер обмена. Перед отправкой в поддержку проверьте их: они могут содержать конфиденциальные сведения.'],
['Review Harness Markdown report copied.', 'Отчёт проверки скопирован в формате Markdown.'],
['You are running a special build of Self-hosted LiveSync. Please be aware of the risks.', 'Вы используете специальную сборку плагина синхронизации. Учитывайте возможные риски.'],
['Plugin is up to date', 'Установлена актуальная версия пилота'],
['Update installed. Restart Obsidian to load the new version.', 'Обновление установлено. Перезапустите Obsidian для загрузки новой версии.'],
['The latest version is installed', 'Установлена актуальная версия'],
['Version ${p0} is available', 'Доступна версия ${p0}'],
['Sign in to your account first', 'Сначала войдите в аккаунт'],
['Sign in to your ArcaLink account first.', 'Сначала войдите в аккаунт ArcaLink.'],
['Could not sign in to the account', 'Не удалось войти в аккаунт'],
['Could not sign in: check your email and password', 'Не удалось войти: проверьте почту и пароль'],
['Server connection is working.', 'Подключение к серверу работает.'],
['The server is temporarily unavailable. Try again later.', 'Сервер временно недоступен. Повторите попытку позже.'],
['Could not contact the server. Check your internet connection.', 'Не удалось связаться с сервером. Проверьте подключение к интернету.'],
['Could not complete the action. Check your connection and account details.', 'Не удалось выполнить действие. Проверьте подключение и данные аккаунта.'],
['Could not change sync mode. Check the connection and try again.', 'Не удалось изменить режим синхронизации. Проверьте подключение и повторите попытку.'],
['Sync error', 'Ошибка синхронизации'],
['No internet connection', 'Нет подключения к интернету'],
['Sync is connected', 'Синхронизация подключена'],
['Sync is paused', 'Синхронизация приостановлена'],
['Automatic sync is disabled', 'Автоматическая синхронизация выключена'],
['Sync is in progress', 'Синхронизация выполняется'],
['Sync is waiting', 'Синхронизация ожидает'],
['Sync is waiting for a connection', 'Синхронизация ожидает подключения'],
['Sync is starting', 'Синхронизация запускается'],
['Server workspace “${p0}” created. The current connection is unchanged.', 'Серверное хранилище «${p0}» создано. Текущее подключение не изменилось.'],
['Server workspace “${p0}” deleted. Local notes and the current connection are preserved.', 'Серверное хранилище «${p0}» удалено. Локальные заметки и текущее подключение сохранены.'],
['Signed in. Workspace “${p0}” is connected.', 'Вход выполнен. Подключено хранилище «${p0}».'],
['Cannot delete a connected workspace', 'Нельзя удалить подключённое хранилище'],
['New server workspace', 'Новое серверное хранилище'],
['Name', 'Название'],
['Create', 'Создать'],
['Cancel', 'Отмена'],
['Continue', 'Продолжить'],
['Personal note encryption', 'Шифрование личных заметок'],
['Cannot delete a connected workspace. It is used by a device, shared folder or Telegram.', 'Нельзя удалить подключённое хранилище. Оно используется устройством, общей папкой или Telegram.'],
['Finish the encryption migration first', 'Сначала завершите перенос шифрования'],
['Choose a workspace', 'Выберите хранилище'],
['Connect a workspace first', 'Сначала подключите хранилище'],
['Enter the encrypted workspace passphrase', 'Введите парольную фразу зашифрованного хранилища'],
['The passphrase must contain at least 12 characters', 'Парольная фраза должна содержать не менее 12 символов'],
['Migration requires an internet connection', 'Для переноса нужен доступ к интернету'],
['Migration is already running', 'Перенос уже выполняется'],
['There is no unfinished migration', 'Незавершённого переноса нет'],
['Finish the previously started migration first', 'Сначала завершите ранее начатый перенос'],
['Confirm that the devices are ready first', 'Сначала подтвердите готовность устройств'],
['Confirm merging the local and server workspaces', 'Подтвердите слияние локального и серверного хранилищ'],
['Migration completed. The original server workspace is preserved. Connect other devices to “${p0}”.', 'Перенос завершён. Старое серверное хранилище сохранено. Подключите остальные устройства к «${p0}».'],
['Folder published. Create an invitation for an editor or viewer.', 'Папка опубликована. Теперь создайте приглашение для редактора или читателя.'],
['Shared folder is offline. Local copies are preserved.', 'Общая папка офлайн. Локальные копии сохранены.'],
['Access to the shared folder is closed. Local copies are preserved.', 'Доступ к общей папке закрыт. Локальные копии сохранены.'],
['Shared folder exceeds its size or owner storage limit. Local changes are preserved.', 'Общая папка превысила лимит размера или места владельца. Локальные правки сохранены.'],
['This folder is read-only. A local edit is saved in the plugin directory.', 'Эта папка доступна только для чтения. Локальная правка сохранена в каталоге плагина.'],
['Moving outside the shared folder is unavailable. Use copying.', 'Перемещение за границы общей папки недоступно. Используйте копирование.'],
['Member access and invitations revoked. Members keep their local copies.', 'Доступ участников и приглашения отозваны. Их локальные копии остаются у них.'],
['Member access revoked', 'Доступ участников отозван'],
['Access to the shared note is closed. The local copy is preserved.', 'Доступ к совместной заметке закрыт. Локальная копия сохранена.'],
['Shared note is offline: local edits will be sent when the connection returns.', 'Совместная заметка офлайн: локальные правки будут отправлены при восстановлении связи.'],
['Access revoked. The local copy is preserved; editing is stopped.', 'Доступ отозван. Локальная копия сохранена; редактирование остановлено.'],
['The external edit coincided with a remote edit. A separate local copy is saved in the plugin directory.', 'Внешняя правка совпала с удалённой. Сохранена отдельная локальная копия в каталоге плагина.'],
['External and remote edits coincided. A local copy is saved in the plugin directory.', 'Внешняя и удалённая правки совпали. Локальная копия сохранена в каталоге плагина.'],
['Shared notes can only be moved within ${p0}', 'Совместные заметки можно перемещать только внутри ${p0}'],
['Bot settings saved. Create a chat link.', 'Настройки бота сохранены. Создайте привязку чата.'],
['Files imported: ${p0}', 'Импортировано файлов: ${p0}'],
['Chat unlinked', 'Чат отвязан'],
['ArcaLink storage is ${p0}% full. Used ${p1} of ${p2}. Free ${p3}. Free up space or upgrade your plan.', 'Хранилище ArcaLink заполнено на ${p0}%. Занято ${p1} из ${p2}. Свободно ${p3}. Освободите место или увеличьте тариф.'],
['Sign in to your pilot account first', 'Сначала войдите в аккаунт пилота'],
['Revocation cancelled', 'Отзыв отменён'],
['Open a shared note', 'Откройте совместную заметку'],
['Invalid path in the shared folder', 'Недопустимый путь в общей папке'],
['Choose an ordinary folder outside other shared folders', 'Выберите обычную папку вне других общих папок'],
['Choose an existing folder with files', 'Выберите существующую папку с файлами'],
['A shared folder can contain up to 100 files', 'В общей папке допускается до 100 файлов'],
['Check file names: the attachment limit is 1 MB', 'Проверьте имена файлов: лимит вложения — 1 МБ'],
['The shared folder is too large: the limit including metadata is 4 MB', 'Содержимое общей папки слишком большое: вместе со служебными данными допускается до 4 МБ'],
['This is an invitation to a note', 'Это приглашение в заметку'],
['Choose an empty folder to preserve your local files', 'Папка должна быть пустой, чтобы сохранить ваши локальные файлы'],
['Invalid shared folder', 'Некорректная общая папка'],
['Shared folder limit: 100 files, up to 1 MB each', 'Лимит общей папки: 100 файлов, до 1 МБ каждый'],
['The shared folder would exceed the 4 MB limit', 'Общая папка превысит лимит 4 МБ'],
['Invalid file name in the shared folder', 'Недопустимое имя файла в общей папке'],
['Invalid name', 'Недопустимое имя'],
['The Telegram folder overlaps a shared folder or contains an invalid path', 'Папка Telegram пересекается с общей папкой или содержит недопустимый путь'],
['Telegram attachment exceeds 10 MB: ${p0}', 'Вложение Telegram превышает 10 МБ: ${p0}'],
['Telegram checksum mismatch', 'Контрольная сумма Telegram не совпала'],
['Imported file conflict: ${p0}', 'Конфликт импортируемого файла: ${p0}'],
['Too many Telegram files', 'Слишком много файлов Telegram'],
['Choose a folder outside shared folders', 'Выберите папку вне общих папок'],
['Use a separate local vault for another account. The current connection is preserved.', 'Для другого аккаунта используйте отдельное локальное хранилище. Текущее подключение сохранено.'],
['Open a separate local Obsidian vault for another server workspace.', 'Для другого серверного хранилища откройте отдельное локальное хранилище Obsidian.'],
['Could not upload notes. The old workspace and local files are preserved. Continue migration in settings.', 'Не удалось загрузить заметки. Старое хранилище и локальные файлы сохранены. Продолжите перенос через настройки.'],
['Migration is incomplete. Automatic sync is stopped and the original workspace is preserved.', 'Перенос не завершён. Автосинхронизация остановлена, исходное хранилище сохранено.'],
['Enter your email address', 'Введите электронную почту'],
['Enter your account password to sign in', 'Введите пароль для входа в аккаунт'],
['Signed in: ${p0}. To connect, choose a workspace on the Workspaces tab.', 'Вход выполнен: ${p0}. Для подключения выберите хранилище на вкладке «Хранилища».'],
['Connection is already in progress', 'Подключение уже выполняется'],
['Finish the workspace merge first', 'Сначала завершите слияние хранилищ'],
['Could not change plugin synchronization. Try again.', 'Не удалось изменить синхронизацию плагинов. Повторите попытку.'],
['Could not read the merge journal. Automatic sync must remain disabled.', 'Не удалось прочитать журнал слияния. Автосинхронизация должна оставаться выключенной.'],
['Finish merging with “${p0}” first', 'Сначала завершите слияние с «${p0}»'],
['An internet connection is required to merge workspaces', 'Для слияния нужен доступ к интернету'],
['The server returned a different workspace', 'Сервер вернул другое хранилище'],
['Could not prepare local notes', 'Не удалось подготовить локальные заметки'],
['Could not download notes. Check the connection and passphrase', 'Не удалось скачать заметки. Проверьте соединение и парольную фразу'],
['Could not upload notes', 'Не удалось загрузить заметки'],
['Could not complete the merge', 'Не удалось завершить слияние'],
['Connected to “${p0}”. The merge is complete and the previous server workspace is preserved.', 'Подключено хранилище «${p0}». Слияние завершено, прежнее серверное хранилище сохранено.'],
['Merging with “${p0}” is incomplete. Automatic sync is paused. Choose this workspace and click “Connect” to continue.', 'Слияние с «${p0}» не завершено. Автосинхронизация приостановлена. Выберите это хранилище и нажмите «Подключить», чтобы продолжить.'],
['Could not verify the encryption key: the server is unavailable', 'Не удалось проверить ключ шифрования: сервер недоступен'],
['The passphrase does not match the selected server workspace. No data was uploaded.', 'Парольная фраза не подходит к выбранному серверному хранилищу. Данные не загружены.'],
['Could not finish processing notes. Reconnect after the current sync has completed.', 'Не удалось завершить обработку заметок. Повторите подключение после завершения текущей синхронизации.'],
['The server workspace version is incompatible. The current connection is preserved.', 'Версия серверного хранилища несовместима. Текущее подключение сохранено.'],
['Could not contact the server. Check your internet connection and retry the check.', 'Не удалось связаться с сервером. Проверьте интернет и повторите проверку.'],
['Could not contact the server. Check your internet connection and retry the check. Reason: ${p0}.', 'Не удалось связаться с сервером. Проверьте интернет и повторите проверку. Причина: ${p0}.'],
['The connection session is invalid or revoked. Click “Sign in” on the “Account” tab, then select a workspace on the “Workspaces” tab and click “Connect”.', 'Сессия подключения недействительна или отозвана. На вкладке «Аккаунт» нажмите «Войти», затем выберите хранилище на вкладке «Хранилища» и нажмите «Подключить».'],
['The server denied access. Update the plugin and sign in again on the “Account” tab. Then select a workspace on the “Workspaces” tab and click “Connect”. If the error persists, contact support.', 'Сервер запретил доступ. Обновите плагин и повторно войдите на вкладке «Аккаунт». Затем выберите хранилище на вкладке «Хранилища» и нажмите «Подключить». Если ошибка остаётся, обратитесь в поддержку.'],
['Server retention period', 'Срок хранения серверных копий'],
['After switching to Free, server copies are kept for 14 days, including shared notes and folders. They are then deleted. Local files and settings are preserved.', 'После перехода на Free серверные копии хранятся 14 суток, включая совместные заметки и общие папки. Затем они удаляются. Локальные файлы и настройки сохраняются.'],
['The server copy of shared notes is unavailable. Local copies are preserved. The connection will resume after renewing Pro.', 'Серверная копия совместных заметок недоступна. Локальные копии сохранены. Подключение возобновится после оплаты Pro.'],
['The server copy of the shared folder is unavailable. Local files are preserved. The connection will resume after renewing Pro.', 'Серверная копия общей папки недоступна. Локальные файлы сохранены. Подключение возобновится после оплаты Pro.'],
['The server copy of shared notes is unavailable. Local copies are preserved; the connection will resume after renewing Pro.', 'Серверная копия совместных заметок недоступна. Локальные копии сохранены; после оплаты Pro подключение возобновится.'],
].map(([def,ru,...aliases])=>[def,{def,ru,...Object.fromEntries(aliases.map((value,i)=>['alias'+i,value]))}]));
